name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Older Python versions on Ubuntu 20.04
          - python-version: 3.7
            os: ubuntu-20.04
          - python-version: 3.8
            os: ubuntu-20.04
          - python-version: 3.9
            os: ubuntu-20.04
          
          # Newer Python versions on latest Ubuntu
          - python-version: '3.10'
            os: ubuntu-latest
          - python-version: '3.11'
            os: ubuntu-latest
          - python-version: '3.12'
            os: ubuntu-latest
          - python-version: '3.13'
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Run tests
      run: |
        # Replace with your actual test command when you have tests
        python -m bugster.cli --help 